//Verilog generated by VPR 0.0.0+16bf4bf5-dirty from post-place-and-route implementation
module up_counter (
    input \clk ,
    input \rst ,
    input \ena ,
    output \counter_out[0] ,
    output \counter_out[1] ,
    output \counter_out[2] ,
    output \counter_out[3] 
);

    //Wires
    wire \clk_output_0_0 ;
    wire \rst_output_0_0 ;
    wire \ena_output_0_0 ;
    wire \latch_counter_out[0]_output_0_0 ;
    wire \latch_counter_out[1]_output_0_0 ;
    wire \latch_counter_out[2]_output_0_0 ;
    wire \latch_counter_out[3]_output_0_0 ;
    wire \lut_n16_output_0_0 ;
    wire \lut_n20_output_0_0 ;
    wire \lut_n24_output_0_0 ;
    wire \lut_n28_output_0_0 ;
    wire \lut_$abc$155$new_n15__output_0_0 ;
    wire \lut_$abc$155$new_n17__output_0_0 ;
    wire \latch_counter_out[3]_clock_0_0 ;
    wire \latch_counter_out[2]_clock_0_0 ;
    wire \latch_counter_out[0]_clock_0_0 ;
    wire \latch_counter_out[1]_clock_0_0 ;
    wire \lut_n16_input_0_1 ;
    wire \lut_n28_input_0_0 ;
    wire \lut_n20_input_0_0 ;
    wire \lut_n24_input_0_0 ;
    wire \lut_$abc$155$new_n17__input_0_0 ;
    wire \lut_$abc$155$new_n15__input_0_0 ;
    wire \lut_n20_input_0_1 ;
    wire \lut_n24_input_0_3 ;
    wire \lut_$abc$155$new_n17__input_0_3 ;
    wire \lut_$abc$155$new_n15__input_0_2 ;
    wire \lut_n20_input_0_2 ;
    wire \lut_n24_input_0_2 ;
    wire \counter_out[0]_input_0_0 ;
    wire \lut_$abc$155$new_n17__input_0_1 ;
    wire \lut_$abc$155$new_n15__input_0_1 ;
    wire \lut_n24_input_0_1 ;
    wire \counter_out[1]_input_0_0 ;
    wire \lut_$abc$155$new_n17__input_0_2 ;
    wire \lut_n28_input_0_2 ;
    wire \counter_out[2]_input_0_0 ;
    wire \lut_n16_input_0_0 ;
    wire \counter_out[3]_input_0_0 ;
    wire \latch_counter_out[3]_input_0_0 ;
    wire \latch_counter_out[0]_input_0_0 ;
    wire \latch_counter_out[1]_input_0_0 ;
    wire \latch_counter_out[2]_input_0_0 ;
    wire \lut_n28_input_0_1 ;
    wire \lut_n16_input_0_2 ;

    //IO assignments
    assign \counter_out[0]  = \counter_out[0]_input_0_0 ;
    assign \counter_out[1]  = \counter_out[1]_input_0_0 ;
    assign \counter_out[2]  = \counter_out[2]_input_0_0 ;
    assign \counter_out[3]  = \counter_out[3]_input_0_0 ;
    assign \clk_output_0_0  = \clk ;
    assign \rst_output_0_0  = \rst ;
    assign \ena_output_0_0  = \ena ;

    //Interconnect
    fpga_interconnect \routing_segment_clk_output_0_0_to_latch_counter_out[3]_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\latch_counter_out[3]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_latch_counter_out[2]_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\latch_counter_out[2]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_latch_counter_out[0]_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\latch_counter_out[0]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_latch_counter_out[1]_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\latch_counter_out[1]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_rst_output_0_0_to_lut_n16_input_0_1  (
        .datain(\rst_output_0_0 ),
        .dataout(\lut_n16_input_0_1 )
    );

    fpga_interconnect \routing_segment_rst_output_0_0_to_lut_n28_input_0_0  (
        .datain(\rst_output_0_0 ),
        .dataout(\lut_n28_input_0_0 )
    );

    fpga_interconnect \routing_segment_rst_output_0_0_to_lut_n20_input_0_0  (
        .datain(\rst_output_0_0 ),
        .dataout(\lut_n20_input_0_0 )
    );

    fpga_interconnect \routing_segment_rst_output_0_0_to_lut_n24_input_0_0  (
        .datain(\rst_output_0_0 ),
        .dataout(\lut_n24_input_0_0 )
    );

    fpga_interconnect \routing_segment_ena_output_0_0_to_lut_$abc$155$new_n17__input_0_0  (
        .datain(\ena_output_0_0 ),
        .dataout(\lut_$abc$155$new_n17__input_0_0 )
    );

    fpga_interconnect \routing_segment_ena_output_0_0_to_lut_$abc$155$new_n15__input_0_0  (
        .datain(\ena_output_0_0 ),
        .dataout(\lut_$abc$155$new_n15__input_0_0 )
    );

    fpga_interconnect \routing_segment_ena_output_0_0_to_lut_n20_input_0_1  (
        .datain(\ena_output_0_0 ),
        .dataout(\lut_n20_input_0_1 )
    );

    fpga_interconnect \routing_segment_ena_output_0_0_to_lut_n24_input_0_3  (
        .datain(\ena_output_0_0 ),
        .dataout(\lut_n24_input_0_3 )
    );

    fpga_interconnect \routing_segment_latch_counter_out[0]_output_0_0_to_lut_$abc$155$new_n17__input_0_3  (
        .datain(\latch_counter_out[0]_output_0_0 ),
        .dataout(\lut_$abc$155$new_n17__input_0_3 )
    );

    fpga_interconnect \routing_segment_latch_counter_out[0]_output_0_0_to_lut_$abc$155$new_n15__input_0_2  (
        .datain(\latch_counter_out[0]_output_0_0 ),
        .dataout(\lut_$abc$155$new_n15__input_0_2 )
    );

    fpga_interconnect \routing_segment_latch_counter_out[0]_output_0_0_to_lut_n20_input_0_2  (
        .datain(\latch_counter_out[0]_output_0_0 ),
        .dataout(\lut_n20_input_0_2 )
    );

    fpga_interconnect \routing_segment_latch_counter_out[0]_output_0_0_to_lut_n24_input_0_2  (
        .datain(\latch_counter_out[0]_output_0_0 ),
        .dataout(\lut_n24_input_0_2 )
    );

    fpga_interconnect \routing_segment_latch_counter_out[0]_output_0_0_to_counter_out[0]_input_0_0  (
        .datain(\latch_counter_out[0]_output_0_0 ),
        .dataout(\counter_out[0]_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_counter_out[1]_output_0_0_to_lut_$abc$155$new_n17__input_0_1  (
        .datain(\latch_counter_out[1]_output_0_0 ),
        .dataout(\lut_$abc$155$new_n17__input_0_1 )
    );

    fpga_interconnect \routing_segment_latch_counter_out[1]_output_0_0_to_lut_$abc$155$new_n15__input_0_1  (
        .datain(\latch_counter_out[1]_output_0_0 ),
        .dataout(\lut_$abc$155$new_n15__input_0_1 )
    );

    fpga_interconnect \routing_segment_latch_counter_out[1]_output_0_0_to_lut_n24_input_0_1  (
        .datain(\latch_counter_out[1]_output_0_0 ),
        .dataout(\lut_n24_input_0_1 )
    );

    fpga_interconnect \routing_segment_latch_counter_out[1]_output_0_0_to_counter_out[1]_input_0_0  (
        .datain(\latch_counter_out[1]_output_0_0 ),
        .dataout(\counter_out[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_counter_out[2]_output_0_0_to_lut_$abc$155$new_n17__input_0_2  (
        .datain(\latch_counter_out[2]_output_0_0 ),
        .dataout(\lut_$abc$155$new_n17__input_0_2 )
    );

    fpga_interconnect \routing_segment_latch_counter_out[2]_output_0_0_to_lut_n28_input_0_2  (
        .datain(\latch_counter_out[2]_output_0_0 ),
        .dataout(\lut_n28_input_0_2 )
    );

    fpga_interconnect \routing_segment_latch_counter_out[2]_output_0_0_to_counter_out[2]_input_0_0  (
        .datain(\latch_counter_out[2]_output_0_0 ),
        .dataout(\counter_out[2]_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_counter_out[3]_output_0_0_to_lut_n16_input_0_0  (
        .datain(\latch_counter_out[3]_output_0_0 ),
        .dataout(\lut_n16_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_counter_out[3]_output_0_0_to_counter_out[3]_input_0_0  (
        .datain(\latch_counter_out[3]_output_0_0 ),
        .dataout(\counter_out[3]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_n16_output_0_0_to_latch_counter_out[3]_input_0_0  (
        .datain(\lut_n16_output_0_0 ),
        .dataout(\latch_counter_out[3]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_n20_output_0_0_to_latch_counter_out[0]_input_0_0  (
        .datain(\lut_n20_output_0_0 ),
        .dataout(\latch_counter_out[0]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_n24_output_0_0_to_latch_counter_out[1]_input_0_0  (
        .datain(\lut_n24_output_0_0 ),
        .dataout(\latch_counter_out[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_n28_output_0_0_to_latch_counter_out[2]_input_0_0  (
        .datain(\lut_n28_output_0_0 ),
        .dataout(\latch_counter_out[2]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$155$new_n15__output_0_0_to_lut_n28_input_0_1  (
        .datain(\lut_$abc$155$new_n15__output_0_0 ),
        .dataout(\lut_n28_input_0_1 )
    );

    fpga_interconnect \routing_segment_lut_$abc$155$new_n17__output_0_0_to_lut_n16_input_0_2  (
        .datain(\lut_$abc$155$new_n17__output_0_0 ),
        .dataout(\lut_n16_input_0_2 )
    );


    //Cell instances
    LUT_K #(
        .K(3),
        .LUT_MASK(8'b00010010)
    ) \lut_n16  (
        .in({
            \lut_n16_input_0_2 ,
            \lut_n16_input_0_1 ,
            \lut_n16_input_0_0 }),
        .out(\lut_n16_output_0_0 )
    );

    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_counter_out[3]  (
        .D(\latch_counter_out[3]_input_0_0 ), 
        .Q(\latch_counter_out[3]_output_0_0 ), 
        .clock(\latch_counter_out[3]_clock_0_0 )
    );
    LUT_K #(
        .K(4),
        .LUT_MASK(16'b1000000000000000)
    ) \lut_$abc$155$new_n17_  (
        .in({
            \lut_$abc$155$new_n17__input_0_3 ,
            \lut_$abc$155$new_n17__input_0_2 ,
            \lut_$abc$155$new_n17__input_0_1 ,
            \lut_$abc$155$new_n17__input_0_0 }),
        .out(\lut_$abc$155$new_n17__output_0_0 )
    );

    LUT_K #(
        .K(3),
        .LUT_MASK(8'b00010100)
    ) \lut_n28  (
        .in({
            \lut_n28_input_0_2 ,
            \lut_n28_input_0_1 ,
            \lut_n28_input_0_0 }),
        .out(\lut_n28_output_0_0 )
    );

    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_counter_out[2]  (
        .D(\latch_counter_out[2]_input_0_0 ), 
        .Q(\latch_counter_out[2]_output_0_0 ), 
        .clock(\latch_counter_out[2]_clock_0_0 )
    );
    LUT_K #(
        .K(3),
        .LUT_MASK(8'b10000000)
    ) \lut_$abc$155$new_n15_  (
        .in({
            \lut_$abc$155$new_n15__input_0_2 ,
            \lut_$abc$155$new_n15__input_0_1 ,
            \lut_$abc$155$new_n15__input_0_0 }),
        .out(\lut_$abc$155$new_n15__output_0_0 )
    );

    LUT_K #(
        .K(3),
        .LUT_MASK(8'b00010100)
    ) \lut_n20  (
        .in({
            \lut_n20_input_0_2 ,
            \lut_n20_input_0_1 ,
            \lut_n20_input_0_0 }),
        .out(\lut_n20_output_0_0 )
    );

    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_counter_out[0]  (
        .D(\latch_counter_out[0]_input_0_0 ), 
        .Q(\latch_counter_out[0]_output_0_0 ), 
        .clock(\latch_counter_out[0]_clock_0_0 )
    );
    LUT_K #(
        .K(4),
        .LUT_MASK(16'b0001010001000100)
    ) \lut_n24  (
        .in({
            \lut_n24_input_0_3 ,
            \lut_n24_input_0_2 ,
            \lut_n24_input_0_1 ,
            \lut_n24_input_0_0 }),
        .out(\lut_n24_output_0_0 )
    );

    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_counter_out[1]  (
        .D(\latch_counter_out[1]_input_0_0 ), 
        .Q(\latch_counter_out[1]_output_0_0 ), 
        .clock(\latch_counter_out[1]_clock_0_0 )
    );

endmodule